version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.5.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks: 
      - elk
  kibana:
    image: kibana:7.5.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
    networks: 
      - elk
  logstash:
    image: logstash:7.5.0
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - 5044:5044
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
    volumes:
      - "./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf"
    depends_on:
      - elasticsearch
    networks: 
      - elk
networks: 
  elk:    
