version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.5.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: on-failure
      placement:
        constraints: [node.role == manager]
    networks: 
      - elk
  kibana:
    image: kibana:7.5.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: on-failure
      placement:
        constraints: [node.role == worker]
    networks: 
      - elk
  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.0
    # command: logstash -f /etc/logstash/conf.d/logstash.conf
    environment: 
      - XPACK.MONITORING.ELASTICSEARCH.HOSTS=http://elasticsearch:9200
      - ELASTIC_PASSWORD=elasticqwe192x
    ports:
      - 5044:5044
    deploy:
      mode: replicated
      restart_policy: on-failure
      replicas: 1
      placement:
        constraints: [node.role == worker]        
    depends_on:
      - elasticsearch
    networks: 
      - elk
volumes: 
  elastic-data:

networks: 
  elk:    
